version: '3'
services:
  spring-boot-nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /usr/local/config/nginx/conf.d:/etc/nginx/conf.d
      - /usr/local/config/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/config/nginx/log:/var/log/nginx
    restart: always
    container_name: spring-boot-nginx
    hostname: spring-boot-nginx
    networks:
      - app
  spring-boot-mysql:
    image: mysql:5.7.17
    ports:
      - 3401:3306
    volumes:
      - /usr/local/config/mysql/model/conf:/etc/mysql
      - /usr/local/config/mysql/model/logs:/var/log/mysql
      - /usr/local/config/mysql/model/data:/var/lib/mysql
    restart: always
    privileged: true
    container_name: spring-boot-mysql
    hostname: spring-boot-mysql
    environment:
      - TZ:Asia/Shanghai
      - MYSQL_ROOT_PASSWORD:root
    networks:
      - app
  spring-boot-nacos:
    image: nacos2.0.2
    ports:
      - 8848:8848
    volumes:
      - /usr/local/config/nacos/logs:/home/nacos/logs
    privileged: true
    restart: always
    container_name: spring-boot-nacos
    hostname: spring-boot-nacos
    environment:
      - PREFER_HOST_MODE:192.168.9.228
      - MODE:standalone
      - SPRING_DATASOURCE_PLATFORM:mysql
      - JVM_XMS:256m
      - JVM_XMX:256m
      - JVM_XMN:256m
      - NACOS_SECURITY_IGNORE_URLS:/**
      - MYSQL_SERVICE_HOST:sh-cdb-ort8kycm.sql.tencentcdb.com
      - MYSQL_SERVICE_PORT:59151
      - MYSQL_SERVICE_USER:*******
      - MYSQL_SERVICE_PASSWORD:*******
      - MYSQL_SERVICE_DB_NAME:nacos
      - TIME_ZONE:Asia/Shanghai
    networks:
      - app
  spring-boot-minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - /usr/local/config/minio/data:/mydata/minio/data
      - /usr/local/config/minio/config:/mydata/minio/config
    restart: always
    privileged: true
    container_name: spring-boot-minio
    hostname: spring-boot-minio
    environment:
      - MINIO_ACCESS_KEY:******* # 账号
      - MINIO_SECRET_KEY:******* #密码
    command:  ['server --console-address ":9090" -address ":9000"  /data']
    networks:
      - app
  spring-boot-elasticsearch7:
    image: elasticsearch:7.16.2
    ports:
      - 10010:9200
      - 10011:9300
    volumes:
      - /usr/local/config/elasticsearch/config:/usr/share/elasticsearch/config
      - /usr/local/config/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/local/config/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    restart: always
    privileged: true
    container_name: spring-boot-elasticsearch7
    hostname: spring-boot-elasticsearch7
    environment:
      - ES_JAVA_OPTS:-Xms512m -Xmx512m
      - discovery.type:single-node
    networks:
      - app
  spring-boot-jenkins:
    image: jenkins/jenkins:2.321-centos7-jdk8
    ports:
      - 10240:8080
      - 10241:50000
    volumes:
      - /usr/local/config/jenkins_home:/var/jenkins_home
    restart: always
    privileged: true
    container_name: spring-boot-jenkins
    hostname: spring-boot-jenkins
    environment:
      - JAVA_OPTS:-server -Xms512m -Xmx512m -XX:PermSize=256m -XX:MaxPermSize=512m
    networks:
      - app
  spring-boot-portainer:
    image: portainer/portainer
    ports:
      - 9001:9000
    volumes:
      - /usr/local/config/portainer/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    container_name: spring-boot-portainer
    hostname: spring-boot-portainer
    networks:
      - app
  spring-boot-redis:
    image: redis:6.0.14
    ports:
      - 6379:6379
    volumes:
      - /usr/local/config/redis/conf/redis.conf:/etc/redis/redis.conf
      - /usr/local/dockr/data:/data
    restart: always
    privileged: true
    container_name: spring-boot-redis
    hostname: spring-boot-redis
    command: ["redis-server","/etc/redis/redis.conf"]
    networks:
      - app
  spring-boot-seata:
    image: seataio/seata-server:1.4.1
    ports:
      - 8091:8091
    volumes:
      - /usr/local/config/seata-server:/seata-server
    restart: always
    privileged: true
    container_name: spring-boot-seata
    hostname: spring-boot-seata
    environment:
      - SEATA_IP:192.168.9.228
      - SEATA_PORT:8091
    networks:
      - app
  spring-boot-sentinel:
    image: bladex/sentinel-dashboard:1.7.1
    ports:
      - 8850:8858
      - 8719:8719
    restart: always
    privileged: true
    container_name: spring-boot-sentinel
    hostname: spring-boot-sentinel
    networks:
      - app
  spring-boot-skywalking-oap-server:
    image: apache/skywalking-oap-server:8.9.1
    ports:
      - 12010:1234
      - 12011:11800
      - 12012:12800
    volumes:
      - /usr/local/config/skywalking/oap-libs/mysql-connector-java-8.0.16.jar:/skywalking/oap-libs/mysql-connector-java-8.0.16.jar
      - /usr/local/config/skywalking/config:/skywalking/config
    restart: always
    privileged: true
    container_name: spring-boot-skywalking-oap-server
    hostname: spring-boot-skywalking-oap-server
    environment:
      - SW_CLUSTER:nacos
      - SW_SERVICE_NAME:skywalking-service
      - SW_CLUSTER_NACOS_HOST_PORT:192.168.9.228:8848
      - SW_CLUSTER_NACOS_NAMESPACE:4fff92eb-d3b0-4603-bffd-d83cfd915eec
      - SW_STORAGE:elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES:192.168.9.228:10010
    networks:
      - app
  spring-boot-skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    ports:
      - 12013:8080
    restart: always
    privileged: true
    container_name: spring-boot-skywalking-ui
    hostname: spring-boot-skywalking-ui
    environment:
      - SW_OAP_ADDRESS:http://192.168.9.228:12012
    networks:
      - app

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/24
          gateway: 172.77.0.1






