version: '3'
services:
  spring-boot-activiti:
    build:
      context: ./spring-cloud/spring-boot-activiti
    ports:
      - 8620:8620
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-activiti/logs:/usr/local/program/spring-cloud/spring-boot-activiti/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-activiti
    hostname: spring-boot-activiti
    networks:
      - app
  spring-boot-bean:
    build:
      context: ./spring-cloud/spring-boot-bean
    ports:
      - 8610:8610
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-bean/logs:/usr/local/program/spring-cloud/spring-boot-bean/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-bean
    hostname: spring-boot-bean
    networks:
      - app
  spring-boot-oa:
    build:
      context: ./spring-cloud/spring-boot-oa
    ports:
      - 8630:8630
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-oa/logs:/usr/local/program/spring-cloud/spring-boot-oa/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-oa
    hostname: spring-boot-oa
    networks:
      - app
  spring-boot-sms:
    build:
      context: ./spring-cloud/spring-boot-sms
    ports:
      - 9120:9120
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-sms/logs:/usr/local/program/spring-cloud/spring-boot-sms/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-sms
    hostname: spring-boot-sms
    networks:
      - app
  spring-boot-web-api:
    build:
      context: ./spring-cloud/spring-boot-web-api
    ports:
      - 9530:9530
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-web-api/logs:/usr/local/program/spring-cloud/spring-boot-web-api/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-web-api
    hostname: spring-boot-web-api
    networks:
      - app
  spring-boot-gateway:
    build:
      context: ./spring-cloud/spring-boot-gateway
    ports:
      - 9190:9190
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-gateway/logs:/usr/local/program/spring-cloud/spring-boot-gateway/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-gateway
    hostname: spring-boot-gateway
    networks:
      - app
  spring-boot-sso:
    build:
      context: ./spring-cloud/spring-boot-sso
    ports:
      - 9110:9110
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-sso/logs:/usr/local/program/spring-cloud/spring-boot-sso/logs
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    container_name: spring-boot-sso
    hostname: spring-boot-sso
    networks:
      - app
networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/24
          gateway: 172.77.0.1






