version: '3'
services:
  spring-boot-activiti:
    container_name: spring-boot-activiti
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_activiti:latest
    ports:
      - 8620:8620
      - 13006:13006
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-activiti/logs:/spring-boot-activiti/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-bean:
    container_name: spring-boot-bean
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_bean:latest
    ports:
      - 8610:8610
      - 13003:13003
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-bean/logs:/spring-boot-bean/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-oa:
    container_name: spring-boot-oa
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_oa:latest
    ports:
      - 8630:8630
      - 13007:13007
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-oa/logs:/spring-boot-oa/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-sms:
    container_name: spring-boot-sms
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_sms:latest
    ports:
      - 9120:9120
      - 9121:9121
      - 9991:9991
      - 13005:13005
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-sms/logs:/spring-boot-sms/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-video:
    container_name: spring-boot-video
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_video:latest
    ports:
      - 8660:8660
      - 6081:6081
      - 13010:13010
      - 14004:14004
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-video/logs:/spring-boot-video/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-web-api:
    container_name: spring-boot-web-api
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_web_api:latest
    ports:
      - 9530:9530
      - 13004:13004
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-web-api/logs:/spring-boot-web-api/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-gateway:
    container_name: spring-boot-gateway
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_gateway:latest
    ports:
      - 9190:9190
      - 13001:13001
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-gateway/logs:/spring-boot-gateway/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
  spring-boot-sso:
    container_name: spring-boot-sso
    image: ccr.ccs.tencentyun.com/spring_boot_cloud/spring_cloud_sso:latest
    ports:
      - 9110:9110
      - 13002:13002
    volumes:
      - /usr/local/program/spring-cloud/spring-boot-sso/logs:/spring-boot-sso/logs
    environment:
      - --spring.profiles.active=prod
    restart: always
    networks:
      - cloud_capp
networks:
  cloud_capp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.0.0/24
        # 版本3中不需要添加 默认添加
        # - gateway: 172.77.0.1






