spring:
  rabbitmq:
    host: 1.15.9.228   #rabbitmq 服务器的地址
    port: 15671           #rabbitmq 服务器端口
    username: z84931842       #rabbitmq 用户名
    password: z916643573       #rabbitmq 密码
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /       #虚拟路径
    listener:
      direct:
        # 用于配置消息是否被重新排队
        default-requeue-rejected: false
      simple:
        # 确认模式 手动
        acknowledge-mode: manual
        #消费者的最小数量
        concurrency: 1
        #消费者的最大数量
        max-concurrency: 20
        #用于配置消费者在处理消息失败时是否将消息重新排队。
        default-requeue-rejected: false
        #是否支持重试
        retry:
          #开启消费者(程序出现异常的情况下会,捕获异常重试将不生效)进行重试
          enabled: true
          #最大重试次数
          max-attempts: 3
          #重试间隔时间 3秒
          multiplier: 2
          #最大间隔时间
          max-interval: 1000ms
          #初始间隔时长
          initial-interval: 1000ms
