
CREATE TABLE video_device (
    id                                  bigint unsigned not null auto_increment COMMENT '主键id',
    device_id                           varchar(50)  NOT NULL COMMENT '设备国标编号',
    name                                varchar(255)  DEFAULT NULL COMMENT '设备名',
    manufacturer                        varchar(255)  DEFAULT NULL COMMENT '生产厂商',
    model                               varchar(255)  DEFAULT NULL COMMENT '型号',
    custom_name                         varchar(255)  DEFAULT NULL COMMENT '风格名词',
    firmware                            varchar(255)  DEFAULT NULL COMMENT '固件版本',
    transport                           tinyint(4)  DEFAULT NULL COMMENT '传输协议 1.UDP 2.TCP',
    ip                                  varchar(50)  DEFAULT NULL COMMENT 'wan地址_ip',
    port                                int unsigned DEFAULT NULL COMMENT 'wan地址_port',
    host_address                        varchar(50)  DEFAULT NULL COMMENT 'wan地址',
    password                            varchar(255)  DEFAULT NULL COMMENT '设备密码',
    sdp_ip                              varchar(50)  DEFAULT NULL COMMENT '收流IP',
    local_ip                            varchar(50)  DEFAULT NULL COMMENT 'SIP交互IP（设备访问平台的IP）',
    charset                             tinyint(4)  default 1 COMMENT '字符集, 1.UTF-8 2.GB2312',
    tree_type                           int unsigned  default 215 COMMENT '树类型 国标规定了两种树的展现方式 216.行政区划：CivilCode 215.业务分组:BusinessGroup',
    geo_coord_sys                       tinyint(4)  default 1 COMMENT '地理坐标系， 目前支持 1.WGS84,2.GCJ02',
    online                              tinyint(4)  default 2 COMMENT '是否在线，1.为在线，0.为离线',
    register_time                       datetime  DEFAULT NULL COMMENT '注册时间',
    renew_time                          datetime  DEFAULT NULL COMMENT '续订时间',
    keepalive_time                      datetime  DEFAULT NULL COMMENT '心跳时间',
    keepalive_interval_time             int default 30 COMMENT '心跳间隔 (最低25秒)',
    stream_mode                         tinyint(4)  DEFAULT 0 COMMENT '数据流传输模式 0.UDP:udp传输 1.TCP-PASSIVE：tcp被动模式 2.TCP-ACTIVE：tcp主动模式',
    expires                             int unsigned DEFAULT 86400 COMMENT '注册有效期（单位：秒 默认1天）',
    mobile_position_submission_interval int unsigned DEFAULT '5' COMMENT '移动设备位置信息上报时间间隔,单位:秒,默认值5 (秒)',
    subscribe_cycle_for_catalog         int unsigned DEFAULT '0' COMMENT '目录订阅周期，0为不订阅 (秒)',
    subscribe_cycle_for_mobile_position int unsigned DEFAULT '0' COMMENT '移动设备位置订阅周期，0为不订阅 (秒)',
    subscribe_cycle_for_alarm           int unsigned DEFAULT '0' COMMENT '报警心跳时间订阅周期，0为不订阅 (秒)',
    ssrc_check                          tinyint(4) DEFAULT '0' COMMENT '是否开启ssrc校验，默认关闭，开启可以防止串流',
    media_server_id                     varchar(255)  DEFAULT NULL COMMENT '流媒体编号 默认为null',
    as_message_channel                  tinyint(4) DEFAULT '0' COMMENT '是否作为消息通道 1.是 0.否',
    has_administrator                   tinyint(4) DEFAULT '0' COMMENT '是否开启超管权限(只有超级管理员才可查看)',
    switch_primary_sub_stream           tinyint(4) DEFAULT '0' COMMENT '是否开启主子码流开关 1.是 0.否',
    create_user_id                      bigint unsigned comment '创建人编号',
    create_time                         datetime  NOT NULL COMMENT '创建时间',
    update_user_id                      bigint unsigned comment '修改人编号',
    update_time                         datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_device_id (device_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='设备信息';

CREATE TABLE video_device_channel (
    id                  bigint unsigned not null auto_increment COMMENT '主键id',
    parent_id           varchar(50)  DEFAULT NULL COMMENT '父级id',
    channel_id          varchar(50)  NOT NULL COMMENT '通道国标编号',
    device_id           varchar(50)  NOT NULL COMMENT '设备国标编号',
    name                varchar(255)  DEFAULT NULL COMMENT '通道名',
    manufacture         varchar(50)  DEFAULT NULL COMMENT '生产厂商',
    model               varchar(50)  DEFAULT NULL COMMENT '型号',
    owner               varchar(50)  DEFAULT NULL COMMENT '设备归属',
    civil_code          varchar(50)  DEFAULT NULL COMMENT '行政区域',
    block               varchar(50)  DEFAULT NULL COMMENT '警区',
    address             varchar(50)  DEFAULT NULL COMMENT '安装地址',
    parental            tinyint(4)  DEFAULT 0 COMMENT '是否有子设备 1有, 0没有',
    safety_way          tinyint(4) DEFAULT 0 COMMENT '信令安全模式  缺省为0; 0:不采用; 2: S/MIME签名方式; 3: S/ MIME加密签名同时采用方式; 4:数字摘要方式',
    register_way        tinyint(4) DEFAULT 1 COMMENT '注册方式 缺省为1;1:符合IETFRFC3261标准的认证注册模 式; 2:基于口令的双向认证注册模式; 3:基于数字证书的双向认证注册模式',
    cert_num            varchar(50)  DEFAULT NULL COMMENT '证书序列号',
    certifiable         tinyint(4) DEFAULT NULL COMMENT '证书有效标识 缺省为0;证书有效标识:0:无效1: 有效',
    err_code            int DEFAULT NULL COMMENT '证书无效原因码',
    end_time            datetime  DEFAULT NULL COMMENT '证书终止有效期',
    secrecy             tinyint(4)  DEFAULT 0 COMMENT '保密属性 缺省为0; 0:不涉密, 1:涉密',
    ip_address          varchar(50)  DEFAULT NULL COMMENT 'IP地址',
    port                int unsigned DEFAULT NULL COMMENT '端口号',
    password            varchar(255)  DEFAULT NULL COMMENT '密码',
    ptz_type            tinyint(4) DEFAULT 0 COMMENT '云台类型 0.未知 1.球机 2.半球 3.固定枪机 4.遥控枪机',
    ptz_type_text       varchar(255) DEFAULT NULL COMMENT '云台类型描述字符串',
    status              tinyint(4) DEFAULT 0 COMMENT '在线/离线， 1在线,0离线',
    longitude           double DEFAULT 0 COMMENT '纬度',
    latitude            double DEFAULT 0 COMMENT '经度',
    longitude_gcj02     double DEFAULT 0 COMMENT '经度 GCJ02',
    latitude_gcj02      double DEFAULT 0 COMMENT '纬度 GCJ02',
    longitude_wgs84     double DEFAULT 0 COMMENT '经度 WGS84',
    latitude_wgs84      double DEFAULT 0 COMMENT '纬度 WGS84',
    sub_count           int unsigned DEFAULT '0' COMMENT '子设备数',
    stream_id           varchar(255)  DEFAULT NULL COMMENT '流唯一编号，存在表示正在直播',
    has_audio           tinyint(4) DEFAULT 0 COMMENT '是否开启音频',
    has_record          tinyint(4) DEFAULT 0 COMMENT '是否开启录像',
    channel_type        tinyint(4) DEFAULT 0 COMMENT '标记通道的类型，0->国标通道 1->直播流通道 2->业务分组/虚拟组织/行政区划',
    business_group_id   varchar(50)  DEFAULT NULL COMMENT '业务分组',
    gps_time            datetime  DEFAULT NULL COMMENT 'GPS的更新时间',
    create_user_id      bigint unsigned comment '创建人编号',
    create_time         datetime  NOT NULL COMMENT '创建时间',
    update_user_id      bigint unsigned comment '修改人编号',
    update_time         datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_channel_id (channel_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='通道信息';


CREATE TABLE video_device_alarm (
    id                  bigint unsigned not null auto_increment COMMENT '主键id',
    device_id           varchar(50)  NOT NULL COMMENT '设备的国标编号',
    channel_id          varchar(50)  NOT NULL COMMENT '通道的国标编号',
    alarm_priority      tinyint(4)  NOT NULL COMMENT '报警级别, 1为一级警情, 2为二级警情, 3为三级警情, 4为四级警情',
    alarm_method        tinyint(4)  DEFAULT NULL COMMENT '报警方式 , 1为电话报警, 2为设备报警, 3为短信报警, 4为 GPS报警, 5为视频报警, 6为设备故障报警,7其他报警;可以为直接组合如12为电话报警或 设备报警-',
    alarm_time          datetime  NOT NULL COMMENT '报警时间',
    alarm_description   varchar(255)  DEFAULT NULL COMMENT '报警内容描述',
    longitude           double DEFAULT NULL COMMENT '经度',
    latitude            double DEFAULT NULL COMMENT '纬度',
    alarm_type          tinyint(4)  DEFAULT NULL COMMENT '报警类型 报警方式为2时， 1-视频丢失报警 2-设备防拆报警 3-存储设备磁盘满报警 4-设备高温报警 5-设备低温报警， 报警方式为5时,取值如下，1-人工视频报警 2-运动目标检测报警 3-遗留物检测报警 4-物体移除检测报警 5-绊线检测报警  6-入侵检测报警 7-逆行检测报警 8-徘徊检测报警 9-流量统计报警 10-密度检测报警 11-视频异常检测报警 12-快速移动报警 报警方式为6时,取值下， 1-存储设备磁盘故障报警 2-存储设备风扇故障报警' ,
    create_user_id      bigint unsigned comment '创建人编号',
    create_time         datetime  NOT NULL COMMENT '创建时间',
    update_user_id      bigint unsigned comment '修改人编号',
    update_time         datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='报警信息' ;

CREATE TABLE video_device_mobile_position (
    id                  bigint unsigned not null auto_increment COMMENT '主键id',
    device_id           varchar(50)  NOT NULL COMMENT '设备Id',
    channel_id          varchar(50)  NOT NULL COMMENT '通道Id',
    device_name         varchar(255)  DEFAULT NULL COMMENT '设备名称',
    time                datetime  NOT NULL COMMENT '通知时间',
    longitude           double default 0.00 COMMENT '经度',
    latitude            double default 0.00 COMMENT '纬度',
    altitude            double  default 0.00 COMMENT '海拔高度',
    speed               double  default 0.00 COMMENT '速度',
    direction           double  default 0.00 COMMENT '方向',
    report_source       varchar(50)  DEFAULT NULL COMMENT '位置信息上报来源（Mobile Position、GPS Alarm）',
    longitude_gcj02     double default 0.00 COMMENT '国内坐标系：经度坐标',
    latitude_gcj02      double default 0.00 COMMENT '国内坐标系：纬度坐标',
    longitude_wgs84     double default 0.00 COMMENT '国内坐标系：经度坐标',
    latitude_wgs84      double default 0.00 COMMENT '国内坐标系：纬度坐标',
    create_user_id      bigint unsigned comment '创建人编号',
    create_time         datetime  NOT NULL COMMENT '创建时间',
    update_user_id      bigint unsigned comment '修改人编号',
    update_time         datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='移动位置信息';


CREATE TABLE video_media_server (
    id                      varchar(255)  NOT NULL COMMENT '主键id',
    ip                      varchar(50)  NOT NULL COMMENT 'IP',
    ssl_status              tinyint(4)  default 0 COMMENT '是否https',
    hook_ip                 varchar(50)  NOT NULL COMMENT 'hook使用的IP（zlm访问WVP使用的IP）',
    sdp_ip                  varchar(50)  NOT NULL COMMENT 'SDP IP',
    stream_ip               varchar(50)  default null COMMENT '流IP',
    http_port               int unsigned default 0 COMMENT 'HTTP端口',
    http_ssl_port           int unsigned default 0 COMMENT 'HTTPS端口',
    rtmp_port               int unsigned default 0 COMMENT 'RTMP端口',
    rtmp_ssl_port           int unsigned default 0 COMMENT 'RTMPS端口',
    rtp_proxy_port          int unsigned default 0 COMMENT 'RTP收流端口（单端口模式有用）',
    rtsp_port               int unsigned default 0 COMMENT 'RTSP端口',
    rtsp_ssl_port           int unsigned default 0 COMMENT 'RTSPS端口',
    auto_config             tinyint(4) default 1 COMMENT '是否开启自动配置ZLM',
    secret                  varchar(50)  default null COMMENT 'ZLM鉴权参数',
    rtp_enable              tinyint(4) default 0 COMMENT '是否使用多端口模式',
    enable                  tinyint(4) default 0 COMMENT '启用状态',
    keepalive_time          datetime  COMMENT '心跳时间',
    status                  tinyint(4) default 0 COMMENT '状态',
    rtp_port_range          varchar(50)  default null COMMENT '多端口RTP收流端口范围',
    record_assist_port      int unsigned default 0 COMMENT 'assist服务端口',
    default_server          tinyint(4) default 0 COMMENT '是否是默认ZLM',
    hook_alive_interval     int unsigned default 30 COMMENT 'keepalive hook触发间隔,单位秒',
    video_play_prefix       varchar(50)  default null COMMENT '流媒体播放 代理前缀',
    video_http_prefix       varchar(50)  default null COMMENT 'video请求时前缀',
    create_user_id          bigint unsigned comment '创建人编号',
    create_time             datetime  NOT NULL COMMENT '创建时间',
    update_user_id          bigint unsigned comment '修改人编号',
    update_time             datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id) USING BTREE,
    UNIQUE KEY idx_http_port (ip,http_port) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='流媒体服务信息';

CREATE TABLE video_parent_platform (
    id                          bigint unsigned not null auto_increment COMMENT '主键id',
    enable                      tinyint(4) default 1 COMMENT '是否启用',
    name                        varchar(255)  DEFAULT NULL COMMENT '名称',
    server_gb_id                varchar(50)  NOT NULL COMMENT 'SIP服务国标编码',
    server_gb_domain            varchar(50)  DEFAULT NULL COMMENT 'SIP服务国标域',
    server_ip                   varchar(50)  DEFAULT NULL COMMENT 'SIP服务IP',
    server_port                 int unsigned DEFAULT NULL COMMENT 'SIP服务端口',
    device_gb_id                varchar(50)  NOT NULL COMMENT '设备国标编号',
    device_ip                   varchar(50)  DEFAULT NULL COMMENT '设备ip',
    device_port                 int unsigned  DEFAULT NULL COMMENT '设备端口',
    username                    varchar(255)  DEFAULT NULL COMMENT 'SIP认证用户名(默认使用设备国标编号)',
    password                    varchar(50)  DEFAULT NULL COMMENT 'SIP认证密码',
    expires                     int unsigned  DEFAULT NULL COMMENT '注册周期 (秒)',
    keep_timeout                int unsigned  DEFAULT NULL COMMENT '心跳周期(秒)',
    transport                   tinyint(4)  default 1 COMMENT '传输协议 1.UDP 2.TCP',
    character_set               tinyint(4)  default 2 COMMENT '字符集, 1.UTF-8 2.GB2312',
    catalog_id                  varchar(50)  NOT NULL COMMENT '默认目录Id,自动添加的通道多放在这个目录下',
    catalog_group               int unsigned DEFAULT '1' COMMENT '目录分组-每次向上级发送通道信息时单个包携带的通道数量，取值1,2,4,8',
    ptz                         tinyint(4) default 1 COMMENT '是否允许云台控制',
    rtcp                        int DEFAULT NULL COMMENT 'RTCP流保活',
    status                      tinyint(4) default 0 COMMENT '在线状态',
    start_offline_push          tinyint(4) DEFAULT '0' COMMENT '点播未推流的设备时是否使用redis通知拉起',
    administrative_division     varchar(50)  default null COMMENT '行政区划',
    tree_type                   int unsigned  default 215 COMMENT '树类型 国标规定了两种树的展现方式 216.行政区划：CivilCode 215.业务分组:BusinessGroup',
    as_message_channel          tinyint(4) DEFAULT '0' COMMENT '是否作为消息通道 1.是 0.否',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_server_gb_id (server_gb_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='平台信息' ;

CREATE TABLE video_platform_catalog (
    id                          varchar(50)  NOT NULL COMMENT '主键id',
    parent_id                   varchar(50)  DEFAULT NULL COMMENT '父级目录ID',
    name                        varchar(255) NOT NULL COMMENT '名称',
    platform_id                 varchar(50)  NOT NULL COMMENT '平台ID',
    civil_code                  varchar(50)  DEFAULT NULL COMMENT '行政区划',
    business_group_id           varchar(50)  DEFAULT NULL COMMENT '目录分组',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='国标级联-目录' ;

CREATE TABLE video_platform_gb_stream (
    id                          bigint unsigned not null auto_increment COMMENT '主键id',
    platform_id                 varchar(50)  NOT NULL COMMENT '平台国标ID',
    catalog_id                  varchar(50)  NOT NULL COMMENT '目录ID',
    gb_stream_id                varchar(50) NOT NULL COMMENT '直播流国标ID',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_gb_stream_id (platform_id,catalog_id,gb_stream_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='国标级联关联直播流' ;

CREATE TABLE video_platform_gb_channel (
    id                          bigint unsigned not null auto_increment COMMENT '主键id',
    platform_id                 varchar(50)  NOT NULL COMMENT '平台国标ID',
    catalog_id                  varchar(50)  NOT NULL COMMENT '目录ID',
    device_channel_id           varchar(50)  NOT NULL COMMENT '通道国标ID',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_device_channel_id (platform_id,catalog_id,device_channel_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='国标级联关联通道信息';


CREATE TABLE video_gb_stream (
     gb_stream_id        bigint unsigned not null auto_increment COMMENT '主键id',
     app                 varchar(255)  NOT NULL COMMENT '应用名',
     stream              varchar(255)  NOT NULL COMMENT '流ID',
     gb_id               varchar(50)  NOT NULL COMMENT '国标ID',
     name                varchar(255)  DEFAULT NULL COMMENT '名称',
     longitude           double default 0.0 COMMENT '经度',
     latitude            double default 0.0 COMMENT '纬度',
     stream_type         tinyint(4)  DEFAULT NULL COMMENT '流类型（1.拉流/2.推流）',
     media_server_id     varchar(50)  DEFAULT NULL COMMENT '流媒体ID',
     create_user_id      bigint unsigned comment '创建人编号',
     create_time         datetime  NOT NULL COMMENT '创建时间',
     update_user_id      bigint unsigned comment '修改人编号',
     update_time         datetime  NOT NULL COMMENT '更新时间',
     PRIMARY KEY (gb_stream_id),
     UNIQUE KEY idx_stream (app,stream) USING BTREE,
     UNIQUE KEY idx_gb_id (gb_id) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='直播流关联国标上级平台' ;

CREATE TABLE video_stream_proxy (
    id                          bigint unsigned not null auto_increment COMMENT '主键id',
    type                        tinyint(4)  NOT NULL COMMENT '类型',
    app                         varchar(255)  NOT NULL COMMENT '应用名',
    stream                      varchar(255)  NOT NULL COMMENT '流ID',
    name                        varchar(255)  DEFAULT NULL COMMENT '名称',
    status                      tinyint(4) NOT NULL COMMENT '状态',
    media_server_id             varchar(50)  DEFAULT NULL COMMENT '流媒体服务ID',
    url                         varchar(255)  DEFAULT NULL COMMENT '拉流地址',
    src_url                     varchar(255)  DEFAULT NULL COMMENT '拉流地址',
    dst_url                     varchar(255)  DEFAULT NULL COMMENT '目标地址',
    timeout_ms                  int unsigned DEFAULT NULL COMMENT '超时时间',
    ffmpeg_cmd_key              varchar(255)  DEFAULT NULL COMMENT 'ffmpeg模板KEY',
    rtp_type                    tinyint(4)  default 1 COMMENT 'rtsp拉流时，拉流方式，0：tcp，1：udp，2：组播',
    enable                      tinyint(4) default 0 COMMENT '是否启用',
    enable_audio                tinyint(4) default 0 COMMENT '是否启用音频',
    enable_mp4                  tinyint(4) default 0 COMMENT '是否启用MP4',
    enable_remove_none_reader   tinyint(4) default 0 COMMENT '是否 无人观看时删除',
    enable_disable_none_reader  tinyint(4) default 1 COMMENT '是否 无人观看时自动停用',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_stream (app,stream)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='拉流代理的信息';

CREATE TABLE video_stream_push (
    id                          bigint unsigned not null auto_increment COMMENT '主键id',
    app                         varchar(255)  NOT NULL COMMENT '应用名',
    stream                      varchar(255)  NOT NULL COMMENT '流id',
    total_reader_count          varchar(50)  DEFAULT NULL COMMENT '观看总人数，包括hls/rtsp/rtmp/http-flv/ws-flv',
    origin_type                 tinyint(4) DEFAULT NULL COMMENT '产生源类型 unknown = 0,rtmp_push=1,rtsp_push=2,rtp_push=3,pull=4,ffmpeg_pull=5,mp4_vod=6,device_chn=7',
    origin_type_str             varchar(50)  DEFAULT NULL COMMENT '产生源类型的字符串描述',
    alive_second                int unsigned DEFAULT NULL COMMENT '存活时间，单位秒',
    media_server_id             varchar(50)  DEFAULT NULL COMMENT '使用的流媒体ID',
    server_id                   varchar(50)  NOT NULL COMMENT '使用的服务ID',
    push_time                   datetime  DEFAULT NULL COMMENT '推流时间',
    status                      tinyint(4) DEFAULT NULL COMMENT '状态',
    push_ing                    tinyint(4) default 0 COMMENT '是否正在推流',
    self                        tinyint(4) default 1 COMMENT '是否自己平台的推流',
    create_user_id              bigint unsigned comment '创建人编号',
    create_time                 datetime  NOT NULL COMMENT '创建时间',
    update_user_id              bigint unsigned comment '修改人编号',
    update_time                 datetime  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY idx_stream (app,stream)
) ENGINE = InnoDB DEFAULT CHARSET = utf8  ROW_FORMAT = DYNAMIC COMMENT ='推流信息';


# 初始化 sql
INSERT INTO `sys_video`.`video_media_server`(`id`, `ip`, `ssl_status`, `hook_ip`, `sdp_ip`, `stream_ip`, `http_port`, `http_ssl_port`, `rtmp_port`, `rtmp_ssl_port`, `rtp_proxy_port`, `rtsp_port`, `rtsp_ssl_port`, `auto_config`, `secret`, `rtp_enable`, `status`, `rtp_port_range`, `record_assist_port`, `default_server`, `hook_alive_interval`, `create_user_id`, `create_time`, `update_user_id`, `update_time`) VALUES ('516549846516848451', '192.168.1.131', 0, '192.168.1.26:8660', '192.168.1.131', '192.168.1.131', 8080, 443, 1935, 19350, 10000, 554, 332, 1, '035c73f7-bb6b-4889-a715-d9eb2d1925cc', 1, 1, '30000-30010', 0, 1, 30, 1, '2023-05-16 14:50:54', NULL, '2023-05-19 16:30:59');
